// demo/cloudlogger-react-ts/src/App.tsx
import React from "react";
import {CloudLogger, CloudLoggerItem} from "@viovnl/cloudlogger";
import "./App.css";

const App: React.FC = () => {
    const clickHandler = () => {
        try {
            const logs: CloudLoggerItem[] = [
                {Name: "Date", Value: "22-10-1994"},
                {Name: "Country", Value: "Netherlands"},
            ];

            CloudLogger.Log(logs);

        } catch (e) {
            console.log("error", e);
        }

    };

    return (
        <>
            <h1>CloudLogger TypeScript Demo</h1>
            <div className="card">
                <button onClick={clickHandler}>Click to send log</button>
            </div>
        </>
    );
};

export default App;

// demo/cloudlogger-angular/src/app/app.component.ts
import { Component, OnInit } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { CloudLogger, CloudLoggerItem } from '@viovnl/cloudlogger';
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [RouterOutlet],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent implements OnInit{
  title = 'cloudlogger-angular';
  constructor() {}

  ngOnInit(): void {
    CloudLogger.Create('your_project_secret');
  }

  onClickLog(): void {
    try {
      const logs: CloudLoggerItem[] = [
        { Name: 'Date', Value: '22-10-1994' },
        { Name: 'Country', Value: 'Netherlands' },
      ];
      CloudLogger.Log(logs);
    } catch (e) {
      console.log('error', e);
    }
  }
}



<main class="main">
  <div class="content">
    <div>
      <h1>CloudLogger Angular Demo</h1>
      <button (click)="onClickLog()">Click to send log</button>
    </div>
  </div>
</main>


<router-outlet />
