// demo/cloudlogger-react-ts/src/App.tsx
import React from "react";
import {CloudLogger} from "@viovnl/cloudlogger";
import "./App.css";

const App: React.FC = () => {
    const clickHandler = () => {
        try {
            CloudLogger.Log([
                {Name: "Date", Value: "22-10-1994"},
                {Name: "Country", Value: "Netherlands"},
            ]);

        } catch (e) {
            console.log("error", e);
        }

    };

    return (
        <>
            <h1>CloudLogger TypeScript Demo</h1>
            <div className="card">
                <button onClick={clickHandler}>Click to send log</button>
            </div>
        </>
    );
};

export default App;

// demo/cloudlogger-nuxtjs/app.vue
<template>
  <div>
    <h1>CloudLogger Nuxt.js Demo</h1>
    <button @click="clickHandler">Click to send log</button>
  </div>
</template>

<script>
import { CloudLogger } from "@viovnl/cloudlogger";

export default {
  mounted() {
    CloudLogger.Create("your_project_secret");
  },
  methods: {
    async clickHandler() {
      try {
        await CloudLogger.Log([
          { Name: "Date", Value: "22-10-1994" },
          { Name: "Country", Value: "Netherlands" },
        ]);
        this.logSent = true;
      } catch (e) {
        console.log("error", e);
      }
    },
  },
};
</script>
